<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Appendix 1 – Advanced Data Analytics Course</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./references.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Appendix-1.html">Appendix 1</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Advanced Data Analytics Course</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-Issue-for-Decision-Making.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Issue for Decision-Making</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-Key-Players-and-Topics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Key Players and Topics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-Imputing-and-Linking-Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Imputing and Linking Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4-Spotting-Weak-Predictive-Signals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Spotting Weak Predictive Signals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-Data-Storage-and-Traceability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data Storage and Traceability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./6-Interpreting-Weak-Predictive-Signals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Interpreting Weak Predictive Signals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./7-Planning-and-Taking-Action.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Planning and Taking Action</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./8-Monitoring-and-Assessing-Progress.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Monitoring and Assessing Progress</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Appendix-1.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Appendix 1</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#augmented-data-analyst" id="toc-augmented-data-analyst" class="nav-link active" data-scroll-target="#augmented-data-analyst">Augmented Data Analyst</a></li>
  <li><a href="#skewness" id="toc-skewness" class="nav-link" data-scroll-target="#skewness">Skewness</a></li>
  <li><a href="#kurtosis" id="toc-kurtosis" class="nav-link" data-scroll-target="#kurtosis">Kurtosis</a></li>
  <li><a href="#coefficient-of-variation" id="toc-coefficient-of-variation" class="nav-link" data-scroll-target="#coefficient-of-variation">Coefficient of Variation</a></li>
  <li><a href="#median-absolute-deviation-mad-and-madmedian" id="toc-median-absolute-deviation-mad-and-madmedian" class="nav-link" data-scroll-target="#median-absolute-deviation-mad-and-madmedian">Median Absolute Deviation MAD and MAD/median</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><strong>Conclusion</strong></a></li>
  <li><a href="#prompts" id="toc-prompts" class="nav-link" data-scroll-target="#prompts">Prompts</a></li>
  <li><a href="#appendix-1-.appendix-.unnumbered" id="toc-appendix-1-.appendix-.unnumbered" class="nav-link" data-scroll-target="#appendix-1-.appendix-.unnumbered">Appendix 1 {.appendix, .unnumbered}</a>
  <ul class="collapse">
  <li><a href="#augmented-data-analyst-1" id="toc-augmented-data-analyst-1" class="nav-link" data-scroll-target="#augmented-data-analyst-1">Augmented Data Analyst</a></li>
  <li><a href="#prompts-1" id="toc-prompts-1" class="nav-link" data-scroll-target="#prompts-1">Prompts</a></li>
  <li><a href="#skewness-1" id="toc-skewness-1" class="nav-link" data-scroll-target="#skewness-1">-&gt; <strong>Skewness</strong></a></li>
  <li><a href="#kurtosis-1" id="toc-kurtosis-1" class="nav-link" data-scroll-target="#kurtosis-1">-&gt; <strong>Kurtosis</strong></a></li>
  <li><a href="#coefficient-of-variation-1" id="toc-coefficient-of-variation-1" class="nav-link" data-scroll-target="#coefficient-of-variation-1">-&gt; <strong>Coefficient of Variation</strong></a></li>
  <li><a href="#median-absolute-deviation-mad-and-madmedian-1" id="toc-median-absolute-deviation-mad-and-madmedian-1" class="nav-link" data-scroll-target="#median-absolute-deviation-mad-and-madmedian-1">-&gt; Median Absolute Deviation MAD and MAD/median</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Appendix 1</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Nathaly Alejandra Páez Ramos</p>
<p>Advance analytics course</p>
<section id="augmented-data-analyst" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="augmented-data-analyst">Augmented Data Analyst</h2>
<pre><code>&gt; delitos_data &lt;- delitos_data[delitos_data$dpto_ccdgo == c ('05'), ] &gt; dim(delitos_data) [1] 49610    91</code></pre>
<p>In this line the 05 code represents the Antioquia department from the Dane data base codes. The line dim(delitos_data) give us a result about how big is our data base, the distribution in rows (49610) and columns (91).</p>
<pre><code>&gt; summary(delitos_data)</code></pre>
<p>This code show us the different kind of crimes, misdemeanors, offenses or infractions in a period of time. For example, for this exercises we choose 24HP that means “hurto a personas en 2024”:</p>
<p><img src="images/clipboard-2144231668.png" class="img-fluid"></p>
<p>Prompt: What is the meaning of the values from sum_24HP that represents the sum of robberies to people in 2024 (where “24” stands for the year).</p>
<p>The values from <strong><code>sum_24HP</code></strong> represent the <strong>sum of robberies to people in 2024</strong>, where:</p>
<ul>
<li><p><strong>Min (0.0000)</strong> → Some areas or time periods had <strong>zero reported robberies</strong>.</p></li>
<li><p><strong>1st Quartile (0.0000)</strong>→ At least <strong>25% of the observations</strong> had zero robberies.</p></li>
<li><p><strong>Median (0.0000)</strong> → At least <strong>50% (half) of the observations had zero robberies</strong>.</p></li>
<li><p><strong>Mean (0.3982)</strong> → The average number of robberies per unit of observation is <strong>less than 0.4</strong>, meaning that while most places/times had zero, some had a high number of incidents.</p></li>
<li><p><strong>3rd Quartile (0.0000)</strong> → <strong>75% of the data points had zero robberies</strong>, emphasizing a high concentration of locations/times with no incidents.</p></li>
<li><p><strong>Max (699.0000)</strong> → There was at least <strong>one location/time period where up to 699 robberies occurred</strong>.</p></li>
</ul>
<section id="interpretation" class="level3">
<h3 class="anchored" data-anchor-id="interpretation">Interpretation</h3>
<ul>
<li><p><strong>Highly skewed distribution</strong>: Most areas/times had no robberies, but some had extremely high numbers.</p></li>
<li><p><strong>Presence of robbery hotspots</strong>: A few locations or time frames had significantly more incidents.</p></li>
<li><p><strong>Possible data issues</strong>: The extreme maximum suggests either a real <strong>crime surge in some areas</strong> or <strong>possible data entry errors</strong>.</p></li>
</ul>
<pre><code>&gt; # quantile &gt; quantile(delitos_data$sum_24HP, probs = seq(0, 1, 0.1), na.rm = TRUE)   0%  10%  20%  30%  40%  50%  60%  70%  80%  90% 100%     0    0    0    0    0    0    0    0    0    1  699 </code></pre>
<p>In quantiles, we can observe that up to 80% of the records have a value of 0, meaning that no robberies were recorded. At the 90th percentile, the value of 1 indicates that only 10% of the observations have a value greater than 1. The maximum value, at the 100th percentile, is 699, which can be interpreted as at least one area having a significantly higher concentration of robberies compared to the majority of the data.</p>
<p><img src="images/clipboard-3158233108.png" class="img-fluid"></p>
<p>In the boxplot, we can observe that the distribution of the variables is asymmetric, confirming that the vast majority of the data has values close to zero. Additionally, the presence of scattered outliers on the right is clearly visible.</p>
</section>
</section>
<section id="skewness" class="level2">
<h2 class="anchored" data-anchor-id="skewness">Skewness</h2>
<pre><code>&gt; paste0('sum_24HP: ', skewness) [1] "sum_24HP: 108.920265681" &gt;  &gt; # function &gt; skewness(delitos_data$sum_24HP, na.rm = TRUE) [1] 108.917</code></pre>
<p>A skewness of 0 or close to 0 indicates a symmetric distribution. If it is greater than 1, the skew is to the right, and if it is negative, the skew is to the left. Consequently, in our data, the skewness value of 108.92 represents extreme asymmetry, providing further evidence of the inequality in the distribution of our data.</p>
</section>
<section id="kurtosis" class="level2">
<h2 class="anchored" data-anchor-id="kurtosis">Kurtosis</h2>
<p><img src="images/clipboard-857239839.png" class="img-fluid"></p>
<p>Image take from: <a href="https://brandata.com.mx/2023/06/09/la-curtosis-que-es/" class="uri">https://brandata.com.mx/2023/06/09/la-curtosis-que-es/</a></p>
<pre><code>&gt; # function &gt; kurtosis(delitos_data$sum_24HP, na.rm = TRUE) [1] 17488.53</code></pre>
<p>The kurtosis calculation yields a value of 17488.53, which is exceptionally high. This suggests a distribution with most values concentrated near the mean while also exhibiting a substantial number of extreme values (outliers). In other words, the distribution has heavy tails, making it highly leptokurtic.</p>
</section>
<section id="coefficient-of-variation" class="level2">
<h2 class="anchored" data-anchor-id="coefficient-of-variation">Coefficient of Variation</h2>
<pre><code>&gt; mean_val &lt;- mean(delitos_data$sum_24HP, na.rm = TRUE)  &gt; print(mean_val)  [1] 0.3981858 &gt; std_dev &lt;- sd(delitos_data$sum_24HP, na.rm = TRUE) &gt; print(std_dev) [1] 4.084402 &gt; lower_bound &lt;- mean_val - std_dev &gt; upper_bound &lt;- mean_val + std_dev &gt; paste0('lower_bound: ', round(lower_bound, 2), ' - upper_bound: ', round(upper_bound, 2)) [1] "lower_bound: -3.69 - upper_bound: 4.48" &gt; percentage_1sd &lt;- (within_1sd / nrow(delitos_data)) * 100 &gt; paste0('within_1sd: ', round(within_1sd, 2), ' - percentage_1sd: ', round(percentage_1sd, 2)) [1] "within_1sd: 48877 - percentage_1sd: 98.52" &gt; paste0('cv: ', round(std_dev / mean_val * 100), 2) [1] "cv: 10262"</code></pre>
<p>Since the coefficient of variation (CV) is used to compare the variability of datasets with different units or widely differing means, and a lower CV indicates less variability relative to the mean, we observe that a CV of 10.262% suggests high variability.</p>
<p>Regarding the mean, which is a measure of central tendency (meaning its calculated value represents the center of the dataset) a result of 0.398 suggests that most areas have few or no recorded events. This implies that the mean may be influenced by a few high values, making it an unreliable representation of the central tendency.</p>
<p>Additionally, the standard deviation, which measures the dispersion of the data relative to the mean, is 4.084 in this case. This indicates that values can vary by approximately ±4.084 from the mean of 0.398, further confirming the high variability in the dataset.</p>
<p>Finally, the ranges within the standard deviation variation (1SD) are calculated using the lower limit as the mean minus the standard deviation and the upper limit as the mean plus the standard deviation. The ranges within the 1SD variation, with a lower limit of -3.69 and an upper limit of 4.48, indicate that the events are highly skewed. This is because most values fall between 0 and 4 (with negative numbers being adjusted to 0). In this dataset, negative values are not possible. If negative values appear, it suggests that the data distribution is highly asymmetric.</p>
<p>Prompt: What is the meaning of having percentages of values within 1SD of “within_1sd: 48877 - percentage_1sd: 98.52”? Explain in a concise paragraph both numbers.</p>
<p>The result <strong>“within_1sd: 48,877 - percentage_1sd: 98.52”</strong> indicates that <strong>48,877 observations (98.52% of the dataset)</strong> fall within one standard deviation (±1SD) of the mean. In a <strong>normally distributed dataset</strong>, approximately <strong>68%</strong> of values should fall within this range. However, in this case, nearly <strong>99% of the values</strong> are concentrated within this narrow range, suggesting that the dataset is <strong>highly skewed</strong> with most values being very close to the mean and a few extreme outliers inflating the standard deviation. This confirms that <strong>the standard deviation is not a reliable measure of spread for these data</strong>, and alternative measures such as percentiles or transformations should be considered.</p>
</section>
<section id="median-absolute-deviation-mad-and-madmedian" class="level2">
<h2 class="anchored" data-anchor-id="median-absolute-deviation-mad-and-madmedian">Median Absolute Deviation MAD and MAD/median</h2>
<pre><code>&gt; median_val &lt;- median(delitos_data$sum_24HP, na.rm = TRUE)  &gt; print(median_val)  [1] 0 &gt; mad_val &lt;- mad(delitos_data$sum_24HP, na.rm = TRUE)  # Compute MAD &gt; print(mad_val) [1] 0 &gt; lower_bound &lt;- median_val - mad_val &gt; upper_bound &lt;- median_val + mad_val &gt; paste0('lower_bound: ', round(lower_bound, 2), ' - upper_bound: ', round(upper_bound, 2)) [1] "lower_bound: 0 - upper_bound: 0" &gt; within_1mad &lt;- sum(delitos_data$sum_24HP &gt;= lower_bound &amp; delitos_data$sum_24HP &lt;= upper_bound, na.rm = TRUE) &gt; percentage_1mad &lt;- (within_1mad / nrow(delitos_data)) * 100 &gt; paste0('within_1mad: ', round(within_1mad, 2), ' - percentage_1mad: ', round(percentage_1mad, 2)) [1] "within_1mad: 42388 - percentage_1mad: 85.44" &gt; # MAD/Median &gt; paste0('MAD/Median: ', round(mad_val / median_val * 100), 2) [1] "MAD/Median: NaN2"</code></pre>
<p>Prompt: What is the interpretation of this results? Explain it.</p>
<section id="interpretation-of-the-results" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-of-the-results"><strong>Interpretation of the Results</strong></h3>
<p>These results confirm that the dataset <strong>is highly concentrated around zero</strong>, with minimal variability for most observations and a small number of extreme outliers. Let’s analyze each statistic in detail:</p>
</section>
<section id="median-median_val" class="level3">
<h3 class="anchored" data-anchor-id="median-median_val"><strong>1. Median (</strong><code>median_val</code><strong>)</strong></h3>
<p>📌 <strong>Value obtained:</strong> <code>0</code><br>
📌 <strong>Interpretation:</strong></p>
<ul>
<li><p>The <strong>median is 0</strong>, meaning that at least <strong>50% of the dataset consists of zero values</strong>.</p></li>
<li><p>This suggests that in at least half of the areas analyzed, <strong>no incidents were recorded in 2024</strong>.</p></li>
<li><p>The fact that the median is <strong>so low compared to the mean (0.398 from previous analysis)</strong> confirms that <strong>a small number of extremely high values (outliers) are inflating the mean</strong>.</p></li>
</ul>
</section>
<section id="median-absolute-deviation-mad" class="level3">
<h3 class="anchored" data-anchor-id="median-absolute-deviation-mad"><strong>2. Median Absolute Deviation (</strong><code>MAD</code><strong>)</strong></h3>
<p>📌 <strong>Value obtained:</strong> <code>0</code><br>
📌 <strong>Interpretation:</strong></p>
<ul>
<li><p>The <strong>MAD (Median Absolute Deviation) measures dispersion around the median</strong>.</p></li>
<li><p>Since <strong>MAD = 0</strong>, this means that <strong>the majority of values are exactly equal to the median (0)</strong>.</p></li>
<li><p>In other words, <strong>most of the dataset consists of zeros, with very few nonzero values</strong>.</p></li>
<li><p><strong>MAD fails to capture variability</strong> because the majority of the data points have the same value.</p></li>
</ul>
</section>
<section id="range-within-1mad" class="level3">
<h3 class="anchored" data-anchor-id="range-within-1mad"><strong>3. Range within</strong> <code>1MAD</code></h3>
<p>📌 <strong>Lower and Upper Bound:</strong> <code>"lower_bound: 0 - upper_bound: 0"</code><br>
📌 <strong>Interpretation:</strong></p>
<ul>
<li><p>The <strong>range defined by 1 MAD</strong> only includes the value <strong>0</strong>, meaning that <strong>all values inside this range are zeros</strong>.</p></li>
<li><p>This further confirms that the dataset <strong>has little dispersion for most observations, except for a few extreme values</strong>.</p></li>
</ul>
</section>
<section id="percentage-of-values-within-1mad" class="level3">
<h3 class="anchored" data-anchor-id="percentage-of-values-within-1mad"><strong>4. Percentage of Values within</strong> <code>1MAD</code></h3>
<p>📌 <strong>Value obtained:</strong> <code>"within_1mad: 42,388 - percentage_1mad: 85.44%"</code><br>
📌 <strong>Interpretation:</strong></p>
<ul>
<li><p><strong>85.44% of observations are exactly 0</strong>.</p></li>
<li><p>This means that only <strong>14.56% of the dataset contains any nonzero values</strong>.</p></li>
<li><p>The data is <strong>highly “zero-inflated”</strong>, meaning that most areas <strong>did not record any incidents in 2024</strong>, while only a few areas had significant crime counts.</p></li>
</ul>
</section>
<section id="mad-median-ratio" class="level3">
<h3 class="anchored" data-anchor-id="mad-median-ratio"><strong>5.</strong> <code>MAD / Median</code> <strong>Ratio</strong></h3>
<p>📌 <strong>Value obtained:</strong> <code>"MAD/Median: NaN2"</code><br>
📌 <strong>Interpretation:</strong></p>
<ul>
<li><p>This calculation <strong>fails (<code>NaN</code>) because the denominator is <code>0</code></strong> (since the median is 0).</p></li>
<li><p>This confirms that <strong>MAD/Median cannot be used as a measure of relative dispersion in this dataset</strong>.</p></li>
<li><p>The presence of so many zeros makes <strong>traditional measures of dispersion ineffective</strong>, and alternative methods should be used.</p></li>
</ul>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion"><strong>Conclusion</strong></h2>
<p>In 85.44% of Antioquia, no personal thefts were recorded, indicating that thefts are concentrated in specific areas of the department. This highlights the need for intervention strategies and measures not only from law enforcement but also through active citizen participation. The state should implement prevention and control activities in collaboration with the community.</p>
</section>
<section id="prompts" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="prompts">Prompts</h2>
<ol type="1">
<li>Prompt: What is the meaning of the values from sum_24HP that represents the sum of robberies to people in 2024 (where “24” stands for the year).</li>
<li>Prompt: What is the meaning of having percentages of values within 1SD of “within_1sd: 48877 - percentage_1sd: 98.52”? Explain in a concise paragraph both numbers.</li>
<li>Prompt: What is the interpretation of this results? Explain it.</li>
</ol>
</section>
<section id="appendix-1-.appendix-.unnumbered" class="level1">
<h1>Appendix 1 {.appendix, .unnumbered}</h1>
<section id="augmented-data-analyst-1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="augmented-data-analyst-1">Augmented Data Analyst</h2>
</section>
<section id="prompts-1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="prompts-1">Prompts</h2>
<hr>
<p><strong>Course:</strong> Advance Analytics of Data.</p>
<p><strong>Student:</strong> Andrés Cervantes Torres.</p>
<p><strong>Professor</strong>: Andrés Pérez-Coronado.</p>
<p>Note: for my analysis I’ve chosen region [88] =&gt; (<strong>archipiélago de san andrés providencia y santa catalina</strong>).</p>
<p>-&gt; delitos_data &lt;- delitos_data[delitos_data$dpto_ccdgo == c (‘88’), ]</p>
<p>Is this line the 88 code represent San Andres y Providencia from DANE data base standared codes.</p>
<p>-&gt; dim(delitos_data)</p>
<p>It is saying the dimension about specific data for the region select previously. In this case 883 rows and 91 colums.</p>
<p>-&gt; summary(delitos_data)</p>
<p>This line permits to know measurements about different kind of crymes against population specifically in region 88. For instance, we can see one of them called “24HP”, whos meaning is theft from persons. This summary shows measures of central tendency: Min: 0, 1st Qu.:0, Median: 0, Mean: 0, 3rd Qu.: 0, Max: 0.</p>
<p>-&gt; quantile(delitos_data$sum_24HP, probs = seq(0, 1, 0.1), na.rm = TRUE)</p>
<p>Prompt: Chat, What does the R “quantile” function tell me, applying the following parameters: # quantile quantile(delitos_data$sum_24HP, probs = seq(0, 1, 0.1), na.rm = TRUE)?</p>
<p>OpenAI GPT-4o</p>
<p>The quantile() function in R is used to calculate the quartiles, quintiles, deciles, or any other percentile of a dataset. In your case, by applying quantile(delitos_data$sum_24HP, probs = seq(0, 1, 0.1), na.rm = TRUE), you are asking to find the deciles of the sum_24HP column of the crímenes_data dataframe.</p>
<p>Here we have results for region 88 (San Andrés y Providencia):</p>
<p>0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%</p>
<p>0 0 0 0 0 0 0 0 0 1 12</p>
<p>This quantile result says we have concentrated major amount of crimes concentrated in some specific municipalities. 92.30% of crimes have been located in 20% of territory.</p>
<p>-&gt; write.csv(delitos_data, file = “delitos_data.csv”, row.names = FALSE)</p>
<p>I’ve applied this line to export “delitos_data” dataset to Excel.</p>
<p>-&gt; boxplot(delitos_data$sum_24HP, main = “Boxplot of PERSONAS”, horizontal = TRUE)</p>
<p>This boxplot represents the distribution of values ​​in sum_24HP, showing the median, quartiles, and any outliers in the distribution.</p>
<p><img src="images/clipboard-3840180970.png" class="img-fluid"></p>
</section>
<section id="skewness-1" class="level2">
<h2 class="anchored" data-anchor-id="skewness-1">-&gt; <strong>Skewness</strong></h2>
<p>Applying skewness to 24HP with value equal to 7.002492, we can say it is extremely high and suggests a strong positive skewness in the distribution of your data.</p>
<p>Prompt: Chat, aún sabiendo que, mean_x = 0.2536806, ¿consideras que un skewness de 7.002492 es muy alto?</p>
<p>A skewness value greater than 1 (or even 2) usually indicates that the distribution is skewed to the right. In your case, a skewness of 7.002492 indicates that most of your values ​​are low (as suggested by a mean of 0.2536806), but there are some very high values ​​(outliers) that are affecting the mean and causing the distribution to be unbalanced.</p>
<p><img src="images/clipboard-1566564623.png" class="img-fluid"></p>
</section>
<section id="kurtosis-1" class="level2">
<h2 class="anchored" data-anchor-id="kurtosis-1">-&gt; <strong>Kurtosis</strong></h2>
<p>In this case applying [kurtosis(delitos_data$sum_24HP, na.rm = TRUE)] we get 65.45428 as result.</p>
<p>Taking this result into account and we knowing that:</p>
<p>A kurtosis of <span class="math inline">\(( 0 )\)</span> (excess kurtosis) indicates tail behavior similar to a normal distribution. Positive kurtosis <span class="math inline">\(( g_2 &gt; 0 )\)</span> signifies heavier tails and more outliers (leptokurtic), while negative kurtosis <span class="math inline">\(( g_2 &lt; 0 )\)</span> indicates lighter tails and fewer outliers (platykurtic).</p>
<p><img src="images/clipboard-3989889599.png" class="img-fluid" width="311"></p>
<p>We can define this Kurtosis as Leptokurtic for 24HP variable since it means we have more outliers.</p>
</section>
<section id="coefficient-of-variation-1" class="level2">
<h2 class="anchored" data-anchor-id="coefficient-of-variation-1">-&gt; <strong>Coefficient of Variation</strong></h2>
<p>The Coefficient of Variation (CV) is a statistical measure that indicates the relative dispersion of data in relation to the mean. It is expressed as a percentage and is used to compare variability between different datasets or measurements.</p>
<p>Performing the calculations in R, I obtained the mean and standard deviation (0.253680634 and 0.969591831), respectively. For this exercise, the instructor suggested using a CV calculated as a percentage. If I apply the formula: round(std_dev / mean_val * 100) The result is 3822%. I wasn’t sure how R performed these calculations, so I transferred the data frame to Microsoft Excel to analyze some aspects.</p>
<p><img src="images/clipboard-1333209121.png" class="img-fluid"></p>
<p>Now I know that R takes all the values, applies an AVERAGE (arithmetic average), and returns the result. I also know that the standard deviation R calculates uses the formula that applies to a sample (x̅), not to the population (μ).</p>
<p>Chat, I’m doing some Advanced Statistical Analysis with R. If the data set I’m analyzing gives me the following result: mean: 0.2536806 standard deviation: 0.9695918 And if with this, the Coefficient of Variation gives me: 3822%. What can I determine from that result? What conclusion can I draw?</p>
<p>OpenAI GPT-4o - start of comment</p>
<p>The <strong>Coefficient of Variation (CV)</strong> is a measure of the relative dispersion of data relative to its mean and is expressed as a percentage. In your case, you have the following results:</p>
<ul>
<li><strong>Mean</strong>: 0.2536806</li>
<li><strong>Standard Deviation</strong>: 0.9695918</li>
<li><strong>Coefficient of Variation (CV)</strong>: 3822%</li>
</ul>
<section id="interpretation-of-the-coefficient-of-variation" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-of-the-coefficient-of-variation">Interpretation of the Coefficient of Variation</h3>
<ol type="1">
<li><strong>Highly Dispersed</strong>:</li>
</ol>
<ul>
<li>A CV of <strong>3822%</strong> suggests that there is a large variability in your data compared to the mean. This means that, on average, the standard deviation is more than 38 times greater than the mean.</li>
</ul>
<ol start="2" type="1">
<li><strong>Mean</strong>:</li>
</ol>
<ul>
<li>Most of your data can vary significantly and could include numerous extreme values ​​or outliers.</li>
<li>Since the mean is relatively low, it suggests that the data is very inconsistent or that there are many zeros in the data set.</li>
</ul>
</section>
<section id="conclusions" class="level3">
<h3 class="anchored" data-anchor-id="conclusions">Conclusions</h3>
<ol type="1">
<li><strong>Data Instability</strong>:</li>
</ol>
<ul>
<li>High variability indicates that the data is not stable, and it may be difficult to make accurate predictions based on the mean.</li>
</ul>
<ol start="2" type="1">
<li><strong>Attitude Toward Analysis</strong>:</li>
</ol>
<ul>
<li>You might consider exploring the data further, looking for outliers, distributions, and other descriptive statistics that can help you understand the behavior of your data.</li>
</ul>
<ol start="3" type="1">
<li><strong>Further Analysis</strong>:</li>
</ol>
<ul>
<li>You could use visualizations (such as histograms or boxplots) to better understand the distribution and variability of the data.</li>
</ul>
<p>Such a high CV is often an indication that further analysis is needed to provide meaningful insights. If you need more information on how to proceed or perform other types of analysis, let me know!</p>
<p>OpenAI GPT-4o - end of comment</p>
<p>Well, as mentioned in the ChatGPT analysis, within the 24HP (Personal Theft) dataset, we definitely have a large number of zeros. This is because we begin to find cases starting at 90% of the data.</p>
<p><img src="images/clipboard-3508930267.png" class="img-fluid"></p>
<p>Now, if we compare the CVs of the different crimes, we can say that there is considerable variability in the occurrence of SUM_24HP (3.82) compared to its mean (0.2536806). We also note that there are other crimes with much higher CVs. Therefore, a CV of 3.82 for SUM_24HP suggests that this illegal act is less predictable and could be affected by external factors or changing conditions in the region.</p>
</section>
</section>
<section id="median-absolute-deviation-mad-and-madmedian-1" class="level2">
<h2 class="anchored" data-anchor-id="median-absolute-deviation-mad-and-madmedian-1">-&gt; Median Absolute Deviation MAD and MAD/median</h2>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./references.html" class="pagination-link" aria-label="References">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">References</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>